apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: lokmanddockerangular 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: lokmanddockerangular 
    spec:
      containers:
        - name: lokmanddockerangular 
          image: kuzeywebdockerangular.azurecr.io/lokmanddockerangular
          ports:
          - containerPort: 443